#ifndef CONSTANTES_H
#define CONSTANTES_H

#define HEIGHT 25
#define WIDTH 80
#define MAX_INIMIGOS 5
#define DARDOS_INICIAL 5
#define PONTOS_INICIAL 0
#define VIDAS_INICIAL 3
#define SAIDA_OCULTA 0
#define SAIDA_LIBERADA 1
#define DURACAO_TIRO 12
#define CICLOS_HEROI 4
#define CICLOS_INIMIGO 4
#define FPS 30
#endif // CONSTANTES_H

#ifndef CARACTERES_H
#define CARACTERES_H

#define CHAR_HEROI 79
#define CHAR_ESPACO 32
#define CHAR_TIRO_V 179
#define CHAR_TIRO_H 196
#endif // CARACTERES_H
